### ISSUE TITLE
Add %[if darkMode]% conditional

### ISSUE THREAD

**Issue by yabdab** [yourhead/s4#46]
Add %[if darkMode]% conditional so stack devs can include a "dark" themed version of edit mode when in Mojave Dark Mode.

**Comment by yourhead** [comment]
i don't think it really makes sense to make this a conditional. it will just be a global CSS class in edit mode. but you'll be able to use it to style your edit mode UI when stacks is doing dark mode.

**Comment by yourhead** [comment]
duplicate of #48
